# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    shared_directory: '%env(string:SHARED_DIRECTORY)%'
    env(SHARED_DIRECTORY): 'shared'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - "../src/DTO/"
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ExchangeRatesCalculatorService:
        arguments:
            $apiKey: '%env(string:EXCHANGERATESAPI_ACCESS_KEY)%'

    App\Command\CalculationCommand:
        arguments:
            $sharedDirectory: '%env(string:SHARED_DIRECTORY)%'

    App\Service\BinCheckerServiceInterface: '@App\Service\BinListCheckerService'
    App\Service\RateCalculatorServiceInterface: '@App\Service\ExchangeRatesCalculatorService'
    App\Service\AmountCalculationServiceInterface: '@App\Service\AmountEURCalculationService'
    App\Service\CommissionCalculationServiceInterface: '@App\Service\CommissionCalculationRoundUpService'
